server:
  port: 8180
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: book-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
aspect:
  timer:
    enable-timer: true
